### ISSUE TITLE
Suggestion: Add Image to the Image URL field instead of the thumbnail url 

### ISSUE THREAD

**Issue by holymode** [Plagiatus/RedditNewFeedDiscordBot#1]

**Comment by Plagiatus** [comment]
Yes, that sounds good. I'd limit it to picture posts though, as i dislike some random image from an article or the text post being displayed. 

I'll play around with this, find what works best and add it in the future. Maybe I can even make it a setting if there are multiple good options.

**Comment by Plagiatus** [comment]
was implemented in dd0e7e31f01c23cb66f4fc917ee99d8e0297aa85, I just forgot to close this issue. :)
